INSERT INTO tutorials (id, slug, title, summary, intro, platforms, difficulty, duration, cover_image, icon, position, steps) VALUES
('11111111-1111-4111-8111-111111111111', 'verificar-erros-hd', 'Verificar erros e otimizar o HD', 'Veja se o disco tem erros e use a ferramenta certa para HD ou SSD.', 'Primeiro descubra qual é o tipo do disco. Depois verifique erros e, somente se for preciso, faça a otimização.', ARRAY['Windows','Linux'], 'Intermediário', 15, '/images/hd-diagnostico.png', 'HardDrive', 1, $json$[
  {"id":"hd-1","title":"Salve os arquivos importantes","body":"Copie documentos e fotos importantes para um pendrive, outro disco ou a nuvem.","warning":"A verificação costuma ser segura, mas o backup protege você se o disco estiver falhando.","expected":"Seus arquivos principais estão guardados em outro lugar."},
  {"id":"hd-2","title":"Descubra se é HD ou SSD","body":"Abra o Gerenciador de Tarefas e selecione o disco.","keys":["Ctrl","Shift","Esc"],"menuPath":["Desempenho","Disco 0"],"media":{"src":"/images/ui/hd-tipo.svg","alt":"Aba Desempenho mostrando que a unidade é SSD","caption":"O tipo do disco aparece abaixo do nome da unidade."},"expected":"Você sabe se a unidade é HD ou SSD."},
  {"id":"hd-3","title":"Abra as ferramentas do disco","body":"Entre nas propriedades do Disco local para encontrar a verificação do Windows.","keys":["⊞ Win","E"],"menuPath":["Este Computador","Disco local","Propriedades","Ferramentas"],"media":{"src":"/images/ui/hd-verificar.svg","alt":"Propriedades do disco com o botão Verificar destacado","caption":"Na aba Ferramentas, procure Verificação de erros."}},
  {"id":"hd-4","title":"Clique em Verificar","body":"Inicie a análise e aguarde o Windows terminar. Você pode continuar usando o computador.","expected":"O Windows informa se encontrou algum erro."},
  {"id":"hd-5","title":"Use o comando somente se precisar","body":"Abra o Terminal como administrador e digite o comando abaixo para corrigir erros encontrados.","command":{"platform":"Windows","code":"chkdsk C: /f","label":"Verificar e corrigir o disco C"},"warning":"Salve seu trabalho. O Windows pode pedir uma reinicialização.","expected":"O comando mostra que o disco foi verificado."},
  {"id":"hd-6","title":"Otimize a unidade correta","body":"Selecione o disco. Em um HD, o Windows organiza os arquivos. Em um SSD, ele faz uma otimização própria.","menuPath":["Pesquisar","Desfragmentar e Otimizar Unidades"],"media":{"src":"/images/ui/hd-otimizar.svg","alt":"Lista de discos com o botão Otimizar","caption":"Confira o Tipo de mídia antes de clicar em Otimizar."},"expected":"O status da unidade aparece como OK."},
  {"id":"hd-7","title":"No Linux, consulte a saúde do disco","body":"O relatório SMART mostra sinais de desgaste ou falha do disco.","command":{"platform":"Linux","code":"sudo smartctl -a /dev/sda","label":"Mostrar a saúde do disco"},"warning":"Se aparecer uma falha, pare e faça backup. Não tente reparar o disco montado.","expected":"O relatório não indica uma falha próxima."}
]$json$::jsonb),
('22222222-2222-4222-8222-222222222222', 'parear-pc-smartphone', 'Parear PC e smartphone', 'Conecte o computador ao celular por Bluetooth e confirme o mesmo código nas duas telas.', 'Deixe o computador e o celular próximos. O pareamento só deve ser confirmado quando os dois mostrarem o mesmo código.', ARRAY['Windows','Linux','Android','iPhone'], 'Iniciante', 10, '/images/bluetooth-pareamento.png', 'Bluetooth', 2, $json$[
  {"id":"bt-1","title":"Aproxime os aparelhos","body":"Deixe o celular a menos de um metro do computador e mantenha-o desbloqueado.","media":{"src":"/images/ui/bluetooth-preparo.svg","alt":"Computador e celular próximos com Bluetooth ligado","caption":"A proximidade ajuda os aparelhos a se encontrarem."},"expected":"Os dois aparelhos estão ligados e próximos."},
  {"id":"bt-2","title":"Ligue o Bluetooth no celular","body":"Abra os atalhos rápidos do celular e toque no símbolo do Bluetooth.","menuPath":["Atalhos rápidos","Bluetooth"],"expected":"O símbolo do Bluetooth aparece ligado."},
  {"id":"bt-3","title":"Abra o Bluetooth no computador","body":"Abra as Configurações do Windows e entre na lista de dispositivos.","keys":["⊞ Win","I"],"menuPath":["Bluetooth e dispositivos"],"expected":"A opção Bluetooth está ativada."},
  {"id":"bt-4","title":"Procure um novo dispositivo","body":"Clique em Adicionar dispositivo e escolha Bluetooth.","menuPath":["Adicionar dispositivo","Bluetooth"],"media":{"src":"/images/ui/bluetooth-adicionar.svg","alt":"Tela para adicionar um dispositivo por Bluetooth","caption":"O computador começa a procurar aparelhos próximos."},"expected":"O nome do celular aparece na lista."},
  {"id":"bt-5","title":"Escolha o seu celular","body":"Clique no nome correto do aparelho.","warning":"Não escolha um aparelho desconhecido, mesmo que o nome seja parecido.","expected":"Um código aparece no computador e no celular."},
  {"id":"bt-6","title":"Compare e confirme o código","body":"Confira todos os números. Se forem iguais, confirme nas duas telas.","media":{"src":"/images/ui/bluetooth-codigo.svg","alt":"O mesmo código aparece no computador e no celular","caption":"Os números devem ser iguais antes de confirmar."},"expected":"O status muda para Conectado ou Pareado."},
  {"id":"bt-7","title":"No Linux, procure pelo terminal","body":"Use estes comandos apenas se a tela de configurações não encontrar o celular.","command":{"platform":"Linux","code":"bluetoothctl\npower on\nscan on","label":"Ligar o Bluetooth e procurar aparelhos"},"expected":"O nome do celular aparece na busca."}
]$json$::jsonb),
('33333333-3333-4333-8333-333333333333', 'restaurar-pc', 'Restaurar o PC com segurança', 'Faça o backup e escolha se deseja manter ou apagar seus arquivos.', 'A restauração reinstala o Windows. Prepare seus arquivos e leia cada escolha antes de chegar ao botão final.', ARRAY['Windows'], 'Avançado', 18, '/images/restauracao-pc.png', 'RotateCcw', 3, $json$[
  {"id":"restore-1","title":"Ligue o computador na tomada","body":"A restauração pode demorar. Conecte o carregador para evitar que o computador desligue.","expected":"O computador está ligado à energia."},
  {"id":"restore-2","title":"Faça uma cópia dos seus arquivos","body":"Copie documentos, fotos e outros arquivos importantes para um pendrive, disco externo ou nuvem.","media":{"src":"/images/ui/restaurar-backup.svg","alt":"Arquivos sendo copiados para um disco externo","caption":"Guarde a cópia fora do computador que será restaurado."},"warning":"Abra alguns arquivos a partir do backup para confirmar que a cópia funciona.","expected":"Seus arquivos importantes estão seguros em outro lugar."},
  {"id":"restore-3","title":"Anote suas contas e licenças","body":"Confira se você sabe a senha da conta Microsoft e guarde licenças de programas pagos.","expected":"Você consegue entrar novamente nas contas depois da restauração."},
  {"id":"restore-4","title":"Abra a tela de recuperação","body":"Entre nas Configurações e procure Restaurar o PC.","keys":["⊞ Win","I"],"menuPath":["Sistema","Recuperação","Restaurar o PC"],"media":{"src":"/images/ui/restaurar-opcoes.svg","alt":"Tela Recuperação com o botão Restaurar o PC","caption":"Este botão abre as opções. A restauração ainda não começa."}},
  {"id":"restore-5","title":"Escolha o que deseja manter","body":"Manter meus arquivos preserva documentos pessoais. Remover tudo apaga também esses documentos.","media":{"src":"/images/ui/restaurar-escolha.svg","alt":"Opções Manter meus arquivos e Remover tudo","caption":"Escolha Manter meus arquivos quando não quiser apagar seus documentos."},"warning":"Remover tudo apaga seus arquivos pessoais. Use essa opção somente com um backup conferido."},
  {"id":"restore-6","title":"Leia o resumo da restauração","body":"Veja quais programas serão removidos e qual disco será alterado.","expected":"O resumo mostra exatamente o que você pretende fazer."},
  {"id":"restore-7","title":"Pare antes do botão final","body":"Neste tutorial, não clique em Restaurar. Use esta etapa apenas para entender o processo.","warning":"Depois do botão final, o computador reinicia e começa a reinstalação.","expected":"Você sabe o que será apagado e está preparado para decidir."}
]$json$::jsonb),
('44444444-4444-4444-8444-444444444444', 'finalizar-processo-mobile', 'Forçar a parada de um aplicativo mobile', 'Feche um aplicativo travado no Android ou reinicie-o no iPhone.', 'Comece tentando fechar o aplicativo normalmente. Use Forçar parada somente se ele continuar travado.', ARRAY['Android','iPhone'], 'Iniciante', 8, '/images/app-mobile.png', 'Smartphone', 4, $json$[
  {"id":"mobile-1","title":"Confirme qual aplicativo travou","body":"Veja se o problema acontece somente em um aplicativo. Teste abrir outra tela do celular.","expected":"Você identificou qual aplicativo não está respondendo."},
  {"id":"mobile-2","title":"Abra os aplicativos recentes","body":"Deslize de baixo para cima e segure. Em celulares com botões, toque no botão de aplicativos recentes.","media":{"src":"/images/ui/mobile-recentes.svg","alt":"Tela com os aplicativos abertos recentemente","caption":"Encontre o cartão do aplicativo que travou."},"expected":"Os aplicativos abertos aparecem em cartões."},
  {"id":"mobile-3","title":"Feche o aplicativo normalmente","body":"Deslize o cartão do aplicativo para cima ou para o lado.","expected":"O aplicativo desaparece da lista de recentes."},
  {"id":"mobile-4","title":"Teste abrir novamente","body":"Abra o aplicativo pela tela inicial e repita a ação que travava.","expected":"O aplicativo volta a responder."},
  {"id":"mobile-5","title":"No Android, abra as informações do app","body":"Se o problema continuar, mantenha o ícone pressionado e toque no símbolo de informações.","menuPath":["Ícone do aplicativo","Informações do app"],"media":{"src":"/images/ui/mobile-info.svg","alt":"Menu do aplicativo com Informações do app destacado","caption":"O nome dessa opção pode mudar conforme o celular."}},
  {"id":"mobile-6","title":"Toque em Forçar parada","body":"Confirme para encerrar o aplicativo até a próxima vez que ele for aberto.","warning":"Uma informação ainda não salva dentro do aplicativo pode ser perdida.","media":{"src":"/images/ui/mobile-forcar.svg","alt":"Botão Forçar parada na tela do aplicativo","caption":"Não toque em Limpar dados. Essa opção apaga informações do aplicativo."},"expected":"O aplicativo para de funcionar em segundo plano."},
  {"id":"mobile-7","title":"No iPhone, deslize o cartão para cima","body":"Abra o seletor de aplicativos e deslize o aplicativo travado para cima.","media":{"src":"/images/ui/mobile-iphone.svg","alt":"Aplicativo do iPhone sendo deslizado para cima","caption":"Em modelos com botão de início, pressione o botão duas vezes."},"expected":"Ao abrir de novo, o aplicativo inicia uma nova sessão."}
]$json$::jsonb),
('55555555-5555-4555-8555-555555555555', 'instalar-impressora-usb', 'Instalar uma impressora USB', 'Conecte a impressora, deixe o sistema instalar e imprima uma página de teste.', 'Comece conferindo a energia e o cabo. Depois veja se o computador reconheceu a impressora antes de procurar outro programa.', ARRAY['Windows','Linux'], 'Iniciante', 12, '/images/impressora-usb.png', 'Printer', 5, $json$[
  {"id":"printer-1","title":"Prepare a impressora","body":"Coloque papel, confira a tinta ou o toner e ligue a impressora.","expected":"A impressora está ligada e não mostra nenhuma luz de erro."},
  {"id":"printer-2","title":"Conecte o cabo USB","body":"Ligue o cabo direto no computador. Evite adaptadores durante o primeiro teste.","media":{"src":"/images/ui/impressora-cabo.svg","alt":"Cabo USB ligando a impressora ao computador","caption":"Use uma porta USB do próprio computador."},"expected":"O cabo está firme nas duas pontas."},
  {"id":"printer-3","title":"Espere o Windows instalar","body":"Aguarde até dois minutos. O Windows costuma instalar a impressora sozinho.","expected":"Uma mensagem informa que o dispositivo está pronto."},
  {"id":"printer-4","title":"Abra Impressoras e scanners","body":"Entre nas Configurações e procure o nome da impressora.","keys":["⊞ Win","I"],"menuPath":["Bluetooth e dispositivos","Impressoras e scanners"],"media":{"src":"/images/ui/impressora-adicionar.svg","alt":"Tela Impressoras e scanners com Adicionar dispositivo","caption":"Se a impressora não aparecer, clique em Adicionar dispositivo."},"expected":"O nome da impressora aparece na lista."},
  {"id":"printer-5","title":"Adicione manualmente se necessário","body":"Clique em Adicionar dispositivo. Se ainda não aparecer, teste outra porta ou outro cabo USB.","warning":"Baixe um programa somente pelo site oficial da fabricante da impressora.","expected":"A impressora aparece como instalada."},
  {"id":"printer-6","title":"Imprima uma página de teste","body":"Abra as propriedades da impressora e escolha Imprimir página de teste.","menuPath":["Impressora","Propriedades da impressora","Imprimir página de teste"],"media":{"src":"/images/ui/impressora-teste.svg","alt":"Botão Imprimir página de teste","caption":"A página confirma que o cabo, a impressora e o programa estão funcionando."},"expected":"A página é impressa sem ficar presa na fila."},
  {"id":"printer-7","title":"No Linux, abra a tela de impressoras","body":"Se a impressora não aparecer nas Configurações, use os comandos abaixo. CUPS é a tela que administra impressoras no Linux.","command":{"platform":"Linux","code":"lpinfo -v\nxdg-open http://localhost:631","label":"Procurar a impressora e abrir o CUPS"},"expected":"A impressora aparece como um dispositivo USB local."}
]$json$::jsonb)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, intro = EXCLUDED.intro, platforms = EXCLUDED.platforms, difficulty = EXCLUDED.difficulty, duration = EXCLUDED.duration, cover_image = EXCLUDED.cover_image, icon = EXCLUDED.icon, position = EXCLUDED.position, steps = EXCLUDED.steps;

INSERT INTO ratings (tutorial_id, visitor_id, score, seeded) SELECT id, '00000000-0000-4000-8000-000000000000', 10, true FROM tutorials ON CONFLICT DO NOTHING;

INSERT INTO comments (id, tutorial_id, parent_id, visitor_id, author, body, created_at) VALUES
('a1111111-1111-4111-8111-111111111111','11111111-1111-4111-8111-111111111111',NULL,'10000000-0000-4000-8000-000000000001','Nina','O aviso sobre SSD foi o que me impediu de usar a ferramenta errada.',now() - interval '2 days'),
('a1111111-1111-4111-8111-111111111112','11111111-1111-4111-8111-111111111111','a1111111-1111-4111-8111-111111111111','10000000-0000-4000-8000-000000000002','Ravi','Também ajudou conferir o tipo pelo Gerenciador de Tarefas.',now() - interval '1 day'),
('a2222222-2222-4222-8222-222222222221','22222222-2222-4222-8222-222222222222',NULL,'20000000-0000-4000-8000-000000000001','Caio','Se o celular não aparecer, desligar e ligar o Bluetooth resolveu aqui.',now() - interval '20 hours'),
('a3333333-3333-4333-8333-333333333331','33333333-3333-4333-8333-333333333333',NULL,'30000000-0000-4000-8000-000000000001','Maya','Gostei de o tutorial parar antes do botão que apaga tudo.',now() - interval '8 hours'),
('a4444444-4444-4444-8444-444444444441','44444444-4444-4444-8444-444444444444',NULL,'40000000-0000-4000-8000-000000000001','Léo','No meu Android o nome é Informações do aplicativo, mas o ícone é igual.',now() - interval '5 hours'),
('a5555555-5555-4555-8555-555555555551','55555555-5555-4555-8555-555555555555',NULL,'50000000-0000-4000-8000-000000000001','Bia','Trocar a porta USB fez a impressora aparecer na hora.',now() - interval '2 hours')
ON CONFLICT (id) DO NOTHING;

INSERT INTO comment_votes (comment_id, visitor_id) VALUES
('a1111111-1111-4111-8111-111111111111','90000000-0000-4000-8000-000000000001'),
('a2222222-2222-4222-8222-222222222221','90000000-0000-4000-8000-000000000001'),
('a5555555-5555-4555-8555-555555555551','90000000-0000-4000-8000-000000000002')
ON CONFLICT DO NOTHING;
